# Generated by Django 4.2.5 on 2024-11-11 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='phone')),
                ('country_code', models.CharField(max_length=20, verbose_name='country_code')),
                ('code_type', models.CharField(choices=[('login', 'login'), ('password_reset', 'password_reset'), ('phone_change', 'phone_change')], max_length=255, verbose_name='code_type')),
                ('is_used', models.BooleanField(default=False, verbose_name='is_used')),
                ('verification_code', models.CharField(db_index=True, max_length=20, verbose_name='verification_code')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='expires_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'VerificationCode',
                'verbose_name_plural': 'VerificationCode',
                'db_table': 'mdl_auth_verification_code',
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='user_id')),
                ('jti', models.CharField(max_length=255, verbose_name='jti')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'TokenBlacklist',
                'verbose_name_plural': 'TokenBlacklist',
                'db_table': 'mdl_auth_token_blacklist',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'jti')},
            },
        ),
    ]
